name: 💡 Feature request
description: Suggest an idea for cram
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem or use case?
      description: What are you trying to do that cram makes hard today?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Proposed solution
    validations:
      required: false
