import type { Selection, OutputFormat, ModelSpec, RankedFile } from './types'

/**
 * Turn a Selection into a single text bundle ready to paste into an LLM.
 *
 * Pure & deterministic: the output depends only on the arguments (no clock,
 * no randomness, no filesystem). Only `selection.included` is rendered, in the
 * order given. The result always ends with a single trailing newline.
 */
export function format(
  selection: Selection,
  opts: { format: OutputFormat; root: string; model: ModelSpec },
): string {
  const dir = baseName(opts.root)
  const tree = renderFileTree(selection.included)

  let body: string
  switch (opts.format) {
    case 'xml':
      body = renderXml(selection, opts.model, dir, tree)
      break
    case 'plain':
      body = renderPlain(selection, opts.model, dir, tree)
      break
    case 'markdown':
    default:
      body = renderMarkdown(selection, opts.model, dir, tree)
      break
  }

  // Guarantee a trailing newline without disturbing verbatim file content.
  return body.endsWith('\n') ? body : body + '\n'
}

const BANNER = 'Generated by cram — https://github.com/cram-cli/cram'
const SEP = '='.repeat(64)

/* ------------------------------------------------------------------ *
 * Shared helpers
 * ------------------------------------------------------------------ */

/** Basename of a path, tolerant of trailing slashes and either separator. */
function baseName(root: string): string {
  const cleaned = root.replace(/[/\\]+$/, '')
  const parts = cleaned.split(/[/\\]/)
  const last = parts[parts.length - 1]
  return last && last.length > 0 ? last : cleaned || root
}

/** Model label plus an "approximate" note when token counts are estimates. */
function modelLine(model: ModelSpec): string {
  return model.approximate
    ? `${model.label} (token counts approximate for this model)`
    : model.label
}

/**
 * Choose a fence long enough to safely enclose `content`: at least 3 backticks,
 * and always one more than the longest run of backticks inside the content, so
 * embedded ``` blocks can never terminate our fence early.
 */
function fenceFor(content: string): string {
  const runs = content.match(/`+/g)
  let longest = 0
  if (runs) {
    for (const run of runs) longest = Math.max(longest, run.length)
  }
  return '`'.repeat(Math.max(3, longest + 1))
}

/** Minimal XML-attribute escaping (double-quotes per contract, plus & and <). */
function escapeAttr(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
}

/* ------------------------------------------------------------------ *
 * File tree builder
 *
 * Builds a nested directory tree from the POSIX `path`s and renders it with
 * 2-space indentation per depth. Directories get a trailing "/". Insertion
 * order is preserved (Maps keep insertion order), so the tree mirrors the
 * order of `included` — deterministic for a given Selection.
 * ------------------------------------------------------------------ */

interface TreeNode {
  children: Map<string, TreeNode>
}

function renderFileTree(files: RankedFile[]): string {
  const root: TreeNode = { children: new Map() }

  for (const file of files) {
    const segments = file.path.split('/').filter((s) => s.length > 0)
    let node = root
    segments.forEach((segment) => {
      let child = node.children.get(segment)
      if (!child) {
        child = { children: new Map() }
        node.children.set(segment, child)
      }
      node = child
    })
  }

  const lines: string[] = []
  walkTree(root, 0, lines)
  return lines.join('\n')
}

function walkTree(node: TreeNode, depth: number, lines: string[]): void {
  const indent = '  '.repeat(depth)
  for (const [name, child] of node.children) {
    if (child.children.size > 0) {
      lines.push(`${indent}${name}/`)
      walkTree(child, depth + 1, lines)
    } else {
      lines.push(`${indent}${name}`)
    }
  }
}

/* ------------------------------------------------------------------ *
 * markdown
 * ------------------------------------------------------------------ */

function renderMarkdown(
  selection: Selection,
  model: ModelSpec,
  dir: string,
  tree: string,
): string {
  const parts: string[] = []

  parts.push(`# ${dir}`)
  parts.push('')
  parts.push(`> ${BANNER}`)
  parts.push('')
  parts.push(`- Files: ${selection.included.length}`)
  parts.push(`- Tokens: ${selection.totalTokens} / ${selection.budget}`)
  parts.push(`- Model: ${modelLine(model)}`)
  parts.push('')

  const treeFence = fenceFor(tree)
  parts.push(`${treeFence}text`)
  parts.push(tree)
  parts.push(treeFence)
  parts.push('')

  for (const file of selection.included) {
    const fence = fenceFor(file.content)
    parts.push(`## ${file.path}`)
    parts.push('')
    parts.push(`${fence}${file.lang}`)
    parts.push(file.content)
    parts.push(fence)
    parts.push('')
  }

  return parts.join('\n')
}

/* ------------------------------------------------------------------ *
 * xml (Claude-optimized, repomix-style)
 * ------------------------------------------------------------------ */

function renderXml(
  selection: Selection,
  model: ModelSpec,
  dir: string,
  tree: string,
): string {
  const parts: string[] = []

  parts.push('<cram>')
  parts.push('  <summary>')
  parts.push(BANNER)
  parts.push(`Directory: ${dir}`)
  parts.push(`Files: ${selection.included.length}`)
  parts.push(`Tokens: ${selection.totalTokens} / ${selection.budget}`)
  parts.push(`Model: ${modelLine(model)}`)
  parts.push('  </summary>')
  parts.push('  <file_tree>')
  parts.push(tree)
  parts.push('  </file_tree>')
  parts.push('  <files>')
  for (const file of selection.included) {
    parts.push(`    <file path="${escapeAttr(file.path)}">`)
    parts.push(file.content)
    parts.push('    </file>')
  }
  parts.push('  </files>')
  parts.push('</cram>')

  return parts.join('\n')
}

/* ------------------------------------------------------------------ *
 * plain
 * ------------------------------------------------------------------ */

function renderPlain(
  selection: Selection,
  model: ModelSpec,
  dir: string,
  tree: string,
): string {
  const parts: string[] = []

  parts.push(BANNER)
  parts.push(`Directory: ${dir}`)
  parts.push(`Files: ${selection.included.length}`)
  parts.push(`Tokens: ${selection.totalTokens} / ${selection.budget}`)
  parts.push(`Model: ${modelLine(model)}`)
  parts.push('')
  parts.push('File tree:')
  parts.push(tree)
  parts.push('')

  for (const file of selection.included) {
    parts.push(SEP)
    parts.push(`FILE: ${file.path}  (${file.tokens} tokens)`)
    parts.push(SEP)
    parts.push(file.content)
  }

  return parts.join('\n')
}
